version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install
  build:
    commands:
      - swc src -d dist --source-maps --copy-files

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
  discard-paths: no
